server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service-api
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceBreaker
                fallbackUri: forward:/fallback/users
            - AddRequestHeader=X-Gateway-Header, gateway

        # SWAGGER
        - id: swagger-all
          uri: http://user-service:8081
          predicates:
            - Path=/swagger-ui/**, /swagger-ui.html, /swagger-resources/**, /v3/api-docs/**, /v3/api-docs
          filters:
            - RewritePath=/v3/api-docs, /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  circuitbreaker:
    instances:
      userServiceBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers