spring:
  datasource:
    url: jdbc:postgresql://postgres-notification:5432/notification_db
    username: postgres
    password: samarin4571730
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: event:org.example.notificationservice.UserEvent
        spring.json.value.default.type: org.example.notificationservice.UserEvent
        auto.offset.reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true